version: '3'
services:
  web:
    build: .
    ports:
      - "5000:80"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=storesDB
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
    postgres_data: